-- supabase/migrations/20251219160000_create_swipes_and_matches.sql

-- This migration creates the necessary tables for the swipe-to-match feature.
--
-- The `swipes` table records every swipe action a user takes on a listing.
-- - `swiper_id`: The user performing the swipe.
-- - `listing_id`: The listing being swiped on.
-- - `direction`: 'left' or 'right'.
-- A unique constraint prevents duplicate swipes on the same listing by the same user.
--
-- The `matches` table stores successful matches between two users.
-- A match is created when two users have swiped right on each other's listings.
-- - `user1_id`, `user2_id`: The two users who have matched.
-- - `listing1_id`, `listing2_id`: The specific listings involved in the match.
-- A unique constraint prevents duplicate matches for the same set of users and listings.

-- Create swipes table
CREATE TABLE public.swipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    swiper_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    listing_id uuid NOT NULL REFERENCES public.listings(id) ON DELETE CASCADE,
    direction text NOT NULL CHECK (direction IN ('left', 'right')),
    CONSTRAINT unique_swipe UNIQUE (swiper_id, listing_id)
);

-- Create matches table
CREATE TABLE public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user1_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    user2_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    listing1_id uuid NOT NULL REFERENCES public.listings(id) ON DELETE CASCADE,
    listing2_id uuid NOT NULL REFERENCES public.listings(id) ON DELETE CASCADE,
    CONSTRAINT unique_match UNIQUE (user1_id, user2_id, listing1_id, listing2_id)
);

-- Enable RLS for the new tables
ALTER TABLE public.swipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- RLS Policies for swipes
-- Users can only insert swipes for themselves.
CREATE POLICY "Users can insert their own swipes"
ON public.swipes
FOR INSERT
WITH CHECK (auth.uid() = swiper_id);

-- Users can only see their own swipes. This is important for privacy.
CREATE POLICY "Users can view their own swipes"
ON public.swipes
FOR SELECT
USING (auth.uid() = swiper_id);

-- RLS Policies for matches
-- Users can only see matches they are a part of.
CREATE POLICY "Users can view their own matches"
ON public.matches
FOR SELECT
USING (auth.uid() = user1_id OR auth.uid() = user2_id);
